// Clean passages — NO blanks, NO pre-written questions
// Groq generates all questions dynamically from clean text.

export const PASSAGES = [
    {
        id: 'pride_prejudice_1',
        title: 'Pride and Prejudice',
        author: 'Jane Austen',
        year: 1813,
        text: `It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters. "My dear Mr. Bennet," said his lady to him one day, "have you heard that Netherfield Park is let at last?" Mr. Bennet replied that he had not. "But it is," returned she; "for Mrs. Long has just been here, and she told me all about it." "Do you not want to know who has taken it?" cried his wife impatiently. "You want to tell me, and I have no objection to hearing it." This was invitation enough.`,
    },
    {
        id: 'moby_dick_1',
        title: 'Moby-Dick',
        author: 'Herman Melville',
        year: 1851,
        text: `Call me Ishmael. Some years ago, never mind how long precisely, having little money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of driving off the spleen and regulating the circulation. Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people's hats off — then, I account it high time to get to sea as soon as I can.`,
    },
    {
        id: 'great_expectations_1',
        title: 'Great Expectations',
        author: 'Charles Dickens',
        year: 1861,
        text: `My father's family name being Pirrip, and my christian name Philip, my infant tongue could make of both names nothing longer or more explicit than Pip. So, I called myself Pip, and came to be called Pip. As I never saw my father or my mother, and never saw any likeness of either of them, my first fancies regarding what they were like were unreasonably derived from their tombstones. The shape of the letters on my father's gave me an odd idea that he was a square, stout, dark man, with curly black hair. From the character and turn of the inscription, "Also Georgiana Wife of the Above," I drew a childlike conclusion that my mother was freckled and sickly.`,
    },
    {
        id: 'scarlet_letter_1',
        title: 'The Scarlet Letter',
        author: 'Nathaniel Hawthorne',
        year: 1850,
        text: `On one side of the portal, and rooted almost at the threshold, was a wild rose-bush, covered, in this month of June, with its delicate gems. Whether it had merely survived out of the stern old wilderness, so long after the fall of the gigantic pines and oaks that originally overshadowed it, or whether it had sprung up under the footsteps of the sainted Ann Hutchinson as she entered the prison-door, we shall not take upon us to determine. Finding it so directly on the threshold of our narrative, which is now about to issue from that inauspicious portal, we could not help adopting the rose-bush as our symbol, and presenting it to the reader, without comment, as the first token of the deep heart of Nature.`,
    },
    {
        id: 'jane_eyre_1',
        title: 'Jane Eyre',
        author: 'Charlotte Bronte',
        year: 1847,
        text: `There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further out-door exercise was now out of the question. I was glad of it: I never liked long walks, especially on chilly afternoons. The said Eliza, John, and Georgiana were now clustered round their mama in the drawing-room: she lay reclined on a sofa by the fireside, and with her darlings about her looked perfectly happy. Me, she had dispensed from joining the group, saying she regretted to be under the necessity of keeping me at a distance until I was endeavouring in good earnest to acquire a more sociable and childlike disposition.`,
    },
    {
        id: 'huck_finn_1',
        title: 'Adventures of Huckleberry Finn',
        author: 'Mark Twain',
        year: 1884,
        text: `You don't know about me without you have read a book by the name of The Adventures of Tom Sawyer; but that ain't no matter. That book was made by Mr. Mark Twain, and he told the truth, mainly. There was things which he stretched, but mainly he told the truth. That is nothing. I never seen anybody but lied one time or another, without it was Aunt Polly, or the widow, or maybe Mary. Now the way that the book winds up is this: Tom and me found the money that the robbers hid in the cave, and it made us rich. We got six thousand dollars apiece, all gold. It was an awful sight of money when it was piled up.`,
    },
    {
        id: 'dorian_gray_1',
        title: 'The Picture of Dorian Gray',
        author: 'Oscar Wilde',
        year: 1890,
        text: `The studio was filled with the rich odour of roses, and when the light summer wind stirred amidst the trees of the garden, there came through the open door the heavy scent of the lilac, or the more delicate perfume of the pink-flowering thorn. From the corner of the divan of Persian saddle-bags on which he was lying, smoking, as was his custom, innumerable cigarettes, Lord Henry Wotton could just catch the gleam of the honey-sweet and honey-coloured blossoms of a laburnum, whose tremulous branches seemed hardly able to bear the burden of a beauty so flame-like as theirs.`,
    },
    {
        id: 'study_in_scarlet_1',
        title: 'A Study in Scarlet',
        author: 'Arthur Conan Doyle',
        year: 1887,
        text: `In the year 1878 I took my degree of Doctor of Medicine of the University of London, and proceeded to Netley to go through the course prescribed for surgeons in the Army. Having completed my studies there, I was duly attached to the Fifth Northumberland Fusiliers as Assistant Surgeon. The regiment was stationed in India at the time, and before I could join it, the second Afghan war had broken out. On landing at Bombay, I learned that my corps had advanced through the passes, and was already deep in the enemy's country. The campaign brought honours and promotion to many, but for me it had nothing but misfortune and disaster.`,
    },
    {
        id: 'origin_of_species_1',
        title: 'On the Origin of Species',
        author: 'Charles Darwin',
        year: 1859,
        text: `When we look to the individuals of the same variety or sub-variety of our older cultivated plants and animals, one of the first points which strikes us is that they generally differ much more from each other than do the individuals of any one species or variety in a state of nature. When we reflect on the vast diversity of the plants and animals which have been cultivated, and which have varied during all ages under the most different climates and treatment, we are driven to conclude that this greater variability is simply due to our domestic productions having been raised under conditions of life not so uniform as those to which the parent-species have been exposed under nature.`,
    },
    {
        id: 'frankenstein_1',
        title: 'Frankenstein',
        author: 'Mary Shelley',
        year: 1818,
        text: `You will rejoice to hear that no disaster has accompanied the commencement of an enterprise which you have regarded with such evil forebodings. I arrived here yesterday, and my first task is to assure my dear sister of my welfare and increasing confidence. I am already far north of London, and as I walk in the streets of Petersburgh, I feel a cold northern breeze play upon my cheeks, which braces my nerves and fills me with delight. Do you understand this feeling? This breeze, which has travelled from the regions towards which I am advancing, gives me a foretaste of those icy climes. Inspirited by this wind of promise, my daydreams become more fervent and vivid.`,
    },
    {
        id: 'tale_two_cities_1',
        title: 'A Tale of Two Cities',
        author: 'Charles Dickens',
        year: 1859,
        text: `It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way. There were a king with a large jaw and a queen with a plain face on the throne of England; there were a king with a large jaw and a queen with a fair face on the throne of France. In both countries it was clearer than crystal to the lords of the State preserves of loaves and fishes, that things in general were settled for ever.`,
    },
    {
        id: 'wuthering_heights_1',
        title: 'Wuthering Heights',
        author: 'Emily Bronte',
        year: 1847,
        text: `I have just returned from a visit to my landlord — the solitary neighbour that I shall be troubled with. This is certainly a beautiful country! In all England, I do not believe that I could have fixed on a situation so completely removed from the stir of society. A perfect misanthropist's heaven — and Mr. Heathcliff and I are such a suitable pair to divide the desolation between us. A capital fellow! He little imagined how my heart warmed towards him when I beheld his black eyes withdraw so suspiciously under their brows, as I rode up, and when his fingers sheltered themselves, with a jealous resolution, still further in his waistcoat, as I announced my name.`,
    },
    {
        id: 'emma_1',
        title: 'Emma',
        author: 'Jane Austen',
        year: 1815,
        text: `Emma Woodhouse, handsome, clever, and rich, with a comfortable home and happy disposition, seemed to unite some of the best blessings of existence; and had lived nearly twenty-one years in the world with very little to distress or vex her. She was the youngest of the two daughters of a most affectionate, indulgent father; and had, in consequence of her sister's marriage, been mistress of his house from a very early period. Her mother had died too long ago for her to have more than an indistinct remembrance of her caresses; and her place had been supplied by an excellent woman as governess, who had fallen little short of a mother in affection.`,
    },
    {
        id: 'dracula_1',
        title: 'Dracula',
        author: 'Bram Stoker',
        year: 1897,
        text: `3 May. Bistritz. Left Munich at 8:35 P.M., on 1st May, arriving at Vienna early next morning; should have arrived at 6:46, but train was an hour late. Buda-Pesth seems a wonderful place, from the glimpse which I got of it from the train and the little time I had there. I feared to go very far from the station, as we had arrived late and would start as near the correct time as possible. The impression I had was that we were leaving the West and entering the East; the most western of splendid bridges over the Danube, which is here of noble width and depth, took us among the traditions of Turkish rule. We left in pretty good time, and came after nightfall to Klausenburgh.`,
    },
    {
        id: 'jekyll_hyde_1',
        title: 'The Strange Case of Dr Jekyll and Mr Hyde',
        author: 'Robert Louis Stevenson',
        year: 1886,
        text: `Mr. Utterson the lawyer was a man of a rugged countenance, that was never lighted by a smile; cold, scanty and embarrassed in discourse; backward in sentiment; lean, long, dusty, dreary, and yet somehow lovable. At friendly meetings, and when the wine was to his taste, something eminently human beaconed from his eye; something indeed which never found its way into his talk, but which spoke not only in these silent symbols of the after-dinner face, but more often and loudly in the acts of his life. He was austere with himself; drank gin when he was alone, to mortify a taste for vintages; and though he enjoyed the theatre, had not crossed the doors of one for twenty years.`,
    },
    {
        id: 'little_women_1',
        title: 'Little Women',
        author: 'Louisa May Alcott',
        year: 1868,
        text: `"Christmas won't be Christmas without any presents," grumbled Jo, lying on the rug. "It's so dreadful to be poor!" sighed Meg, looking down at her old dress. "I don't think it's fair for some girls to have plenty of pretty things, and other girls nothing at all," added little Amy, with an injured sniff. "We've got Father and Mother, and each other," said Beth contentedly from her corner. The four young faces on which the firelight shone brightened at the cheerful words, but darkened again as Jo said sadly, "We haven't got Father, and shall not have him for a long time." She didn't say "perhaps never," but each silently added it, thinking of Father far away, where the fighting was.`,
    },
    {
        id: 'crime_punishment_1',
        title: 'Crime and Punishment',
        author: 'Fyodor Dostoevsky',
        year: 1866,
        text: `On an exceptionally hot evening early in July a young man came out of the garret in which he lodged in S. Place and walked slowly, as though in hesitation, towards K. bridge. He had successfully avoided meeting his landlady on the staircase. His garret was under the roof of a high, five-storied house and was more like a cupboard than a room. The landlady who provided him with garret, dinners, and attendance, lived on the floor below, and every time he went out he was obliged to pass her kitchen, the door of which invariably stood open. And each time he passed, the young man had a sick, frightened feeling, which made him scowl and feel ashamed.`,
    },
    {
        id: 'les_miserables_1',
        title: 'Les Misérables',
        author: 'Victor Hugo',
        year: 1862,
        text: `In 1815, M. Charles-François-Bienvenu Myriel was Bishop of Digne. He was an old man of about seventy-five years of age; he had occupied the see of Digne since 1806. Although this detail has no connection whatever with the real substance of what we call the story, it may not be useless, in the interest of exactness in all things, to mention here the rumours and remarks which had been made concerning him on his first arrival in the diocese. True or false, that which is said of men often occupies as important a place in their lives, and above all in their destinies, as that which they do. M. Myriel was the son of a councillor of the parliament of Aix; hence he belonged to the nobility of the bar.`,
    },
    {
        id: 'heart_of_darkness_1',
        title: 'Heart of Darkness',
        author: 'Joseph Conrad',
        year: 1899,
        text: `The Nellie, a cruising yawl, swung to her anchor without a flutter of the sails, and was at rest. The flood had made, the wind was nearly calm, and being bound down the river, the only thing for it was to come to and wait for the turn of the tide. The sea-reach of the Thames stretched before us like the beginning of an interminable waterway. In the offing the sea and the sky were welded together without a joint, and in the luminous space the tanned sails of the barges drifting up with the tide seemed to stand still in red clusters of canvas sharply peaked, with gleams of varnished sprits. A haze rested on the low shores that ran out to sea in vanishing flatness. The air was dark above Gravesend, and farther back still seemed condensed into a mournful gloom.`,
    },
    {
        id: 'tom_sawyer_1',
        title: 'The Adventures of Tom Sawyer',
        author: 'Mark Twain',
        year: 1876,
        text: `"TOM!" No answer. "TOM!" No answer. "What's gone with that boy, I wonder? You TOM!" No answer. The old lady pulled her spectacles down and looked over them about the room; then she put them up and looked out under them. She seldom or never looked through them for so small a thing as a boy; they were her state pair, the pride of her heart, and were built for "style," not service — she could have seen through a pair of stove-lids just as well. She looked perplexed for a moment, and then said, not fiercely, but still loud enough for the furniture to hear: "Well, I lay if I get hold of you I'll —" She did not finish, for by this time she was bending down and punching under the bed with the broom.`,
    },
    {
        id: 'sense_sensibility_1',
        title: 'Sense and Sensibility',
        author: 'Jane Austen',
        year: 1811,
        text: `The family of Dashwood had long been settled in Sussex. Their estate was large, and their residence was at Norland Park, in the centre of their property, where, for many generations, they had lived in so respectable a manner as to engage the general good opinion of their surrounding acquaintance. The late owner of this estate was a single man, who lived to a very advanced age, and who for many years of his life, had a constant companion and housekeeper in his sister. But her death, which happened ten years before his own, produced a great alteration in his home; for to supply her loss, he invited and received into his house the family of his nephew Mr. Henry Dashwood, the legal inheritor of the Norland estate, and the person to whom he intended to bequeath it.`,
    },
    {
        id: 'oliver_twist_1',
        title: 'Oliver Twist',
        author: 'Charles Dickens',
        year: 1839,
        text: `Among other public buildings in a certain town, which for many reasons it will be prudent to refrain from mentioning, and to which I will assign no fictitious name, there is one anciently common to most towns, great or small: to wit, a workhouse; and in this workhouse was born, on a day and date which I need not trouble myself to repeat, inasmuch as it can be of no possible consequence to the reader, in this stage of the business at all events, the item of mortality whose adventures will form the subject of these pages. For a long time after it was ushered into this world of sorrow and trouble, by the parish surgeon, it remained a matter of considerable doubt whether the child would survive to bear any name at all.`,
    },
    {
        id: 'count_monte_cristo_1',
        title: 'The Count of Monte Cristo',
        author: 'Alexandre Dumas',
        year: 1844,
        text: `On the 24th of February, 1815, the look-out at Notre-Dame de la Garde signalled the three-master, the Pharaon from Smyrna, Trieste, and Naples. As usual, a pilot put off immediately, and rounding the Château d'If, got on board the vessel between Cape Morgiou and Rion island. Immediately, and according to custom, the ramparts of Fort Saint-Jean were covered with spectators; it is always an event at Marseilles for a ship to come into port, especially when this ship, like the Pharaon, has been built, rigged, and laden at the old Phocee docks, and belongs to an owner of the city. The ship drew on and had safely passed the strait, which some volcanic shock has made between the Calasareigne and Jaros islands.`,
    },
    {
        id: 'yellow_wallpaper_1',
        title: 'The Yellow Wallpaper',
        author: 'Charlotte Perkins Gilman',
        year: 1892,
        text: `It is very seldom that mere ordinary people like John and myself secure ancestral halls for the summer. A colonial mansion, a hereditary estate, I would say a haunted house, and reach the height of romantic felicity — but that would be asking too much of fate! Still I will proudly declare that there is something queer about it. Else, why should it be let so cheaply? And why have stood so long untenanted? John laughs at me, of course, but one expects that in marriage. John is practical in the extreme. He has no patience with faith, an intense horror of superstition, and he scoffs openly at any talk of things not to be felt and seen and put down in figures.`,
    },
    {
        id: 'north_south_1',
        title: 'North and South',
        author: 'Elizabeth Gaskell',
        year: 1855,
        text: `"Edith!" said Margaret, gently, "Edith!" But Edith had fallen into a soft slumber, and Margaret would not waken her. Instead, she continued to look out of the window, down into the quiet street below, where the lamps were just being lit, and the passers-by were hurrying homewards through the chill evening air. She had come up to London with her cousin only the week before, and she was still unused to its noise and bustle. She had been brought up in a country parsonage, far from the busy stir of towns; and the contrast between that peaceful life and this restless, eager London world struck her with a kind of pain, as though she had been suddenly plunged into deep water after years of walking on solid ground.`,
    },
    {
        id: 'sherlock_speckled_1',
        title: 'The Adventure of the Speckled Band',
        author: 'Arthur Conan Doyle',
        year: 1892,
        text: `On glancing over my notes of the seventy odd cases in which I have during the last eight years studied the methods of my friend Mr. Sherlock Holmes, I find many tragic, some comic, a large number merely strange, but none commonplace; for, working as he did rather for the love of his art than for the acquirement of wealth, he refused to associate himself with any investigation which did not tend towards the unusual, and even the fantastic. Of all these varied cases, however, I cannot recall any which presented more singular features than that which was associated with the well-known Surrey family of the Roylotts of Stoke Moran. The events in question occurred in the early days of my association with Holmes, when we were sharing rooms as bachelors in Baker Street.`,
    },
    {
        id: 'metamorphosis_1',
        title: 'The Metamorphosis',
        author: 'Franz Kafka',
        year: 1915,
        text: `One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, were waving helplessly before his eyes. What has happened to me? he thought. It was not a dream. His room, a proper human room although a little too small, lay peacefully between its four familiar walls.`,
    },
    {
        id: 'portrait_of_a_lady_1',
        title: 'The Portrait of a Lady',
        author: 'Henry James',
        year: 1881,
        text: `Under certain circumstances there are few hours in life more agreeable than the hour dedicated to the ceremony known as afternoon tea. There are circumstances in which, whether you partake of the tea or not — some people of course never do — the situation is in itself delightful. Those that I have in mind in beginning to unfold this simple history offered an admirable setting to an innocent pastime. The implements of the little feast had been disposed upon the lawn of an old English country-house, in what I should call the perfect middle of a splendid summer afternoon. Part of the afternoon had waned, but much of it was left, and what was left was of the finest and rarest quality.`,
    },
    {
        id: 'tess_durbervilles_1',
        title: 'Tess of the d\'Urbervilles',
        author: 'Thomas Hardy',
        year: 1891,
        text: `On an evening in the latter part of May a middle-aged man was walking homeward from Shaston to the village of Marlott, in the adjoining Vale of Blakemore or Blackmoor. The pair of legs that carried him were rickety, and there was a bias in his gait which inclined him somewhat to the left of a straight line. He occasionally gave a smart nod, as if in confirmation of some opinion, though he was not thinking of anything in particular. An empty egg-basket was slung upon his arm, the nap of his hat was ruffled, a coloured handkerchief was loosely knotted about his neck. He was a skilful and well-practised walker, and had clearly done much business on foot.`,
    },
    {
        id: 'middlemarch_1',
        title: 'Middlemarch',
        author: 'George Eliot',
        year: 1871,
        text: `Miss Brooke had that kind of beauty which seems to be thrown into relief by poor dress. Her hand and wrist were so finely formed that she could wear sleeves not less bare of style than those in which the Blessed Virgin appeared to Italian painters; and her profile as well as her stature and bearing seemed to gain the more dignity from her plain garments, which by the side of provincial fashion gave her the impressiveness of a fine quotation from the Bible, or from one of our elder poets, in a paragraph of to-day's newspaper. She was usually spoken of as being remarkably clever, but with the addition that her sister Celia had more common-sense. Nevertheless, Celia wore scarcely more trimmings; and it was only to close observers that her dress had the distinction of simplicity.`,
    },
];

// ── Rhetorical Synthesis note sets ───────────────────────────────────────────
// These are used when Groq picks the rhetorical_synthesis question type.
// No passage text — just bullet notes and a goal.

export const NOTE_SETS = [
    {
        id: 'darwin_notes',
        title: 'Charles Darwin — On the Origin of Species',
        author: 'Charles Darwin',
        year: 1859,
        type: 'rhetorical_synthesis',
        notes: [
            'Charles Darwin published On the Origin of Species in 1859.',
            'The book introduced the theory of evolution by natural selection.',
            'Darwin argued that species best adapted to their environment survive and reproduce.',
            'The book was controversial because it challenged prevailing religious and scientific views.',
            'Darwin spent over 20 years gathering evidence before publishing.',
        ],
    },
    {
        id: 'mary_shelley_notes',
        title: 'Mary Shelley — Frankenstein',
        author: 'Mary Shelley',
        year: 1818,
        type: 'rhetorical_synthesis',
        notes: [
            'Mary Shelley wrote Frankenstein in 1818 at the age of 20.',
            'The novel is considered one of the first works of science fiction.',
            'Shelley began writing the story as part of a ghost story competition with Lord Byron and Percy Shelley.',
            'The novel explores themes of ambition, responsibility, and the consequences of playing God.',
            'The creature in the novel is never given a name by its creator, Victor Frankenstein.',
        ],
    },
    {
        id: 'austen_notes',
        title: 'Jane Austen — Pride and Prejudice',
        author: 'Jane Austen',
        year: 1813,
        type: 'rhetorical_synthesis',
        notes: [
            'Jane Austen published Pride and Prejudice in 1813.',
            'The novel was originally titled First Impressions.',
            'Austen wrote the first draft when she was just 21 years old.',
            'The novel satirizes the social expectations placed on women in early 19th-century England.',
            'Pride and Prejudice is one of the best-selling novels in history with over 20 million copies sold.',
        ],
    },
    {
        id: 'dickens_notes',
        title: 'Charles Dickens — A Tale of Two Cities',
        author: 'Charles Dickens',
        year: 1859,
        type: 'rhetorical_synthesis',
        notes: [
            'Charles Dickens published A Tale of Two Cities in 1859.',
            'The novel is set during the French Revolution in London and Paris.',
            'It is one of the best-selling novels of all time with over 200 million copies sold.',
            'Dickens based the character of Sydney Carton on a play he had performed in himself.',
            'The novel opens with one of the most famous lines in English literature.',
        ],
    },
    {
        id: 'twain_notes',
        title: 'Mark Twain — Adventures of Huckleberry Finn',
        author: 'Mark Twain',
        year: 1884,
        type: 'rhetorical_synthesis',
        notes: [
            'Mark Twain published Adventures of Huckleberry Finn in 1884.',
            'The novel is narrated in the first person by its protagonist, Huck Finn.',
            'Ernest Hemingway called it the source of all modern American literature.',
            'The novel was controversial upon publication for its depiction of race and society.',
            'Twain wrote the novel over seven years, setting it aside for extended periods.',
        ],
    },
    {
        id: 'doyle_notes',
        title: 'Arthur Conan Doyle — Sherlock Holmes',
        author: 'Arthur Conan Doyle',
        year: 1887,
        type: 'rhetorical_synthesis',
        notes: [
            'Arthur Conan Doyle introduced Sherlock Holmes in A Study in Scarlet in 1887.',
            'Holmes is one of the most portrayed fictional characters in film and television history.',
            'Doyle based Holmes on his university professor Dr. Joseph Bell, known for his powers of observation.',
            'Doyle grew tired of Holmes and killed him off in 1893, but public pressure forced him to bring the character back.',
            'Holmes is known for the phrase "Elementary, my dear Watson," though this exact line never appears in the original stories.',
        ],
    },
    {
        id: 'wilde_notes',
        title: 'Oscar Wilde — The Picture of Dorian Gray',
        author: 'Oscar Wilde',
        year: 1890,
        type: 'rhetorical_synthesis',
        notes: [
            'Oscar Wilde published The Picture of Dorian Gray in 1890.',
            'The novel was initially published in Lippincott\'s Monthly Magazine.',
            'The story follows a young man whose portrait ages while he remains young.',
            'The novel was considered scandalous upon publication for its moral ambiguity.',
            'Wilde later revised and expanded the novel, adding a preface defending art for art\'s sake.',
        ],
    },
    {
        id: 'bronte_notes',
        title: 'Charlotte Brontë — Jane Eyre',
        author: 'Charlotte Brontë',
        year: 1847,
        type: 'rhetorical_synthesis',
        notes: [
            'Charlotte Brontë published Jane Eyre in 1847 under the pen name Currer Bell.',
            'The novel was an immediate commercial success upon publication.',
            'Jane Eyre is considered an early feminist novel for its focus on the inner life and independence of its female protagonist.',
            'Brontë drew on her own experiences at a harsh boarding school when writing the Lowood sections.',
            'The novel pioneered the use of first-person narrative to explore a character\'s psychological depth.',
        ],
    },
];